### PR TITLE
Added translation to the State machine tutorial

### PR DESCRIPTION
**Pull request by mmarramarco**
Added C# code example to the state machine. The GDScript portion still works as intended, although I don't know if the GD only version of Godot will run the GD portion without caring about the CS bits.

### CODE REVIEW

**Comment by NathanLovato** [comment]
Could you make a dedicated godot mono project? We'd better separate the two, following what official Godot demos do.

You can create a new godot-csharp/ directory next to the godot/ one in the repo.

Thanks much for taking the time, it's much appreciated!

**Comment by mmarramarco** [comment]
It's my pleasure to work with you :) I'm at work right now, I'll set a reminder and try to update it at noon or tonight.

**Comment by NathanLovato** [comment]
Thanks, I'll test and merge today; gotta set up Godot Mono and got a lot on my plate right now

**Comment by NathanLovato** [comment]
Thanks much for the contribution!

**Pull request merged**
