### PR TITLE
translated the ECS tutorial to CSharp. Fixed a shader issue.

### PR DESCRIPTION
**Pull request by mmarramarco**
Translated the ECS project to a C# project, following the guidelines and project organization previously discussed.
In the GD project, the shader was NOT updating, causing an error, and the project was confusing to try : nothing was moving on the batteries. I fixed it, but please verify it follows the intended behaviour. 
The fix was also made in the C# project.

Thanks again for those awesome tutorials ❤️

### CODE REVIEW

**Comment by NathanLovato** [comment]
Ping @Razoric480, could you take care of this PR's review?

**Comment by Razoric480** [comment]
Doesn't seem to be working quite right. Only the first battery appears to be charging up and the others don't react.

**Comment by mmarramarco** [comment]
@Razoric480 you're absolutely correct! I had forgotten to correctly parameters the batteries in the editor, as well as recalculating the efficiency inside the batteries. Everything should be running smoothly now :) Tell me if I missed anything otherwise.

**Comment by Razoric480** [comment]
Looks right to me now. Thanks!

**Comment by mmarramarco** [comment]
You're welcome, happy to help!

**Pull request merged**
